### ISSUE TITLE
Question regarding the completion of this library

### ISSUE THREAD

**Issue by Nickypoo** [MingweiSamuel/Zyra#3]
Do you have an estimation completion on the new version of this library?

**Comment by MingweiSamuel** [comment]
The library is completely functional for v3 (there may be bugs ofc). It's just some argument orders in the endpoints and fixing the enums that I want to do before the release

**Comment by MingweiSamuel** [comment]
And of course also update the documentation as well for the new changes

**Comment by Nickypoo** [comment]
Do you have a date on the new  release?

**Comment by MingweiSamuel** [comment]
Before 2017/07/24 ... probably.

**Comment by MingweiSamuel** [comment]
Still trying to get a new key after the key changes for CI, but I'll use a spare production key for now..

**Comment by MingweiSamuel** [comment]
Released 1.1.0
