### ISSUE TITLE
Need to be updated for new keys ?

### ISSUE THREAD

**Issue by Nickypoo** [MingweiSamuel/Zyra#7]
Riot keys have been updated to this.

Rate Limit(s): 
20 requests every 1 seconds 
100 requests every 2 minutes 
Note that rate limits are enforced per region. For example, with the above rate limit, you could make 500 requests every 10 minutes to both NA and EUW endpoints simultaneously

**Comment by MingweiSamuel** [comment]
Yup. Can still set the keys manually but will update the defaults. (Also I've applied for a "project" key so the integration tests will still run)

**Comment by MingweiSamuel** [comment]
The plan now is to automatically detect rate limits and avoid specifying them explicitly #8
